### ISSUE TITLE
Wiki collaboration

### ISSUE THREAD

**Issue by kristiank** [GIRA/PhysicalBits#27]
I can't push to the wiki and I can't figure out if I cloned it in a wrong way or if I am simply missing the correct rights for editing it.

I cloned it like:
```bash
$ git clone https://github.com/GIRA/UziScript.wiki.git
Cloning into 'UziScript.wiki'...
remote: Enumerating objects: 6, done.
Unpacking objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 6
```

The repo's remotes look like:
```bash
$ git remote -v
origin	https://github.com/GIRA/UziScript.wiki.git (fetch)
origin	https://github.com/GIRA/UziScript.wiki.git (push)
```

And I try to push like this:
```bash
$ git push
Username for 'https://github.com': kristiank
Password for 'https://kristiank@github.com': 
remote: Permission to GIRA/UziScript.wiki.git denied to kristiank.
fatal: unable to access 'https://github.com/GIRA/UziScript.wiki.git/': The requested URL returned error: 403
```

**Comment by RichoM** [comment]
Sorry, I never used the github wiki before. I just changed the wiki settings and I think you should be able to edit the wiki directly now.

![github_wiki_settings](https://user-images.githubusercontent.com/1226503/74233232-11339a80-4ca9-11ea-8f08-3c9f26497161.png)

**Comment by kristiank** [comment]
it works as is evident in the edit https://github.com/GIRA/PhysicalBits/wiki/Home/0f6b4319331a28e9c79bcf3e9f4e38f6e7901107

**Comment by RichoM** [comment]
Nice! I totally forgot about the wiki. I'll start writing some ideas for future work there. Feel free to comment or add your own
