### ISSUE TITLE
 In the firmware upload I found this unfriendly message

### ISSUE THREAD

**Issue by jennifferch** [GIRA/PhysicalBits#38]
El Sketch usa 23876 bytes (74%) del espacio de almacenamiento del programa. El máximo es 32256 bytes.
Las variables Globales usan 1901 bytes (92%) de la memoria dinámica, dejando 147 bytes para las variables locales. El máximo es 2048 bytes.

**Comment by RichoM** [comment]
I added a message in the [Installing the firmware](https://gira.github.io/PhysicalBits/DOWNLOAD.html#installing-the-firmware) section explaining that this is not a problem.

This issue will also go away when we implement automatic firmware upload.
